### ISSUE TITLE
[Bug]: build error when `"type": "module"` in `package.json`

### ISSUE THREAD

**Issue by haiweilian** [web-infra-dev/rspress#344]
### Version

```sh
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 137.62 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.123
    Edge: 113.0.1774.35
    Firefox: 110.0
    Safari: 15.6.1
  npmPackages:
    @rspress/plugin-preview: ^1.6.0 => 1.6.0 
    rspress: ^1.6.0 => 1.6.0
```

### Details

当在 `package.json` 添加 `"type": "module"` 时打包错误。当我项目是 Pure ESM  时我需要加上它。

### package.json

```json
{
  "type": "module",
}
```

### error info
```text
error   Referencerequire is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/lianhaiwei/Code/source/taggd-manager/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at 89968 (file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:646917)
    at i (file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:862526)
    at 91083 (file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:213091)
    at i (file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:862526)
    at 54855 (file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:418370)
    at i (file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:862526)
    at 15152 (file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:644277)
    at i (file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:862526)
    at file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:863949
    at file:///Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js:1:863977
warn    Failed to load SSR bundle: /Users/lianhaiwei/Code/source/taggd-manager/doc_build/ssr/bundles/main.js, fallback to CSR.
success Pages rendered in 62 ms.
```

### Reproduce link

https://github.com/haiweilian/taggd-manager/tree/master

### Reproduce Steps

npm install

npm run docs:build

**Comment by chenjiahan** [comment]
看起来是 SSG 产生的 bundles/main.js 被当作 ESM 加载，所以 SSG 失败了。

这里应该需要把 bundles/main.js 修改为 bundles/main.cjs，或者生成一个临时的 package.json 来覆盖根目录的 package.json type: 'module'.

**Comment by haiweilian** [comment]
是的，vitepress 那边是 esm，可以通过配置文件后缀名解决两种模块同时使用。
当我在输出目录手动加一个 package.json 是可以成功的，通过改后缀名的方式不可以。

https://vitepress.dev/guide/getting-started#prerequisites

> VitePress is an ESM-only package. Don't use require() to import it, and make sure your nearest package.json contains "type": "module", or change the file extension of your relevant files like .vitepress/config.js to .mjs/.mts. Refer to [Vite's troubleshooting guide](http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only) for more details. Also, inside async CJS contexts, you can use await import('vitepress') instead.

**Comment by 10Derozan** [comment]
I think builder need autoExtensions too! @chenjiahan
