### ISSUE TITLE
[Bug]: html-to-text can't parse document with text `<constructor>`

### ISSUE THREAD

**Issue by sumy7** [web-infra-dev/rspress#401]
### Version

```sh
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1
    Memory: 60.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.2
  npmPackages:
    @rspress/shared: ^1.7.4 => 1.7.4 
    rspress: ^1.7.4 => 1.7.4
```

### Details

where a markdown file contains `<constructor>`
![image](https://github.com/web-infra-dev/rspress/assets/3841747/a0ff6669-68f3-48a2-a2a9-4f02d5d17a0e)
html-to-text process report `Arguments must be arrays.`

🔥 Rspress v1.7.4

file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+parseley@0.12.1/node_modules/parseley/lib/parseley.mjs:270
        throw new Error('Arguments must be arrays.');
              ^

Error: Arguments must be arrays.
    at _compareArrays (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+parseley@0.12.1/node_modules/parseley/lib/parseley.mjs:270:15)
    at compareSpecificity (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+parseley@0.12.1/node_modules/parseley/lib/parseley.mjs:265:12)
    at comparatorPreferLast (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+selderee@0.11.0/node_modules/selderee/lib/selderee.mjs:429:18)
    at Picker.pick1 (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+selderee@0.11.0/node_modules/selderee/lib/selderee.mjs:417:17)
    at recursiveWalk (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs:1233:46)
    at f1 (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs:19:44)
    at formatInline (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs:1306:3)
    at recursiveWalk (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs:1235:9)
    at f1 (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs:19:44)
    at formatPre (file:///Users/sumy/SumyBlog-rspress/node_modules/.pnpm/registry.npmmirror.com+html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs:1583:3)

Node.js v18.18.2
 ELIFECYCLE  Command failed with exit code 1.

### Reproduce link

none

### Reproduce Steps

1. create new md document
2. add content 

```
\```javascript
<constructor>
\```
```

3. pnpm run dev

**Comment by sanyuan0704** [comment]
v1.7.5 has solved the problem

**Comment by sumy7** [comment]
Thx ❤,  `<constructor>` works in v1.7.5.
