### ISSUE TITLE
[Bug]: Unknown option `-c`

### ISSUE THREAD

**Issue by 2heal1** [web-infra-dev/rspress#524]
### Version

```sh
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 221.17 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 16.1
  npmPackages:
    rspress: 1.9.2 => 1.9.2
```

### Details

execute `npx rspress dev -c rspress.config.ts` , and it will throw below error:

```bash
file:///rspress-demo/node_modules/.pnpm/cac@6.7.14/node_modules/cac/dist/index.mjs:400
          throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
                ^

CACError: Unknown option `-c`
    at Command.checkUnknownOptions (file:///rspress-demo/node_modules/.pnpm/cac@6.7.14/node_modules/cac/dist/index.mjs:400:17)
    at CAC.runMatchedCommand (file:///rspress-demo/node_modules/.pnpm/cac@6.7.14/node_modules/cac/dist/index.mjs:598:13)
    at CAC.parse (file:///rspress-demo/node_modules/.pnpm/cac@6.7.14/node_modules/cac/dist/index.mjs:537:12)
    at file:///rspress-demo/node_modules/.pnpm/rspress@1.9.2_webpack@5.89.0/node_modules/rspress/dist/index.js:154:5
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
```

### Reproduce link

https://github.com/2heal1/rspress-demo

### Reproduce Steps

1. `pnpm install`
2. npx rspress dev -c rspress.config.ts

**Comment by 2heal1** [comment]
add an extra info: `-- config` can work .
